apiVersion: apps/v1
kind: Deployment
metadata:
  name: snp500-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: snp500-backend
  template:
    metadata:
      labels:
        app: snp500-backend
    spec:
      containers:
        - name: backend
          image: <your-backend-image>:latest
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: snp500-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snp500-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: <your-rds-endpoint>
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: <your-db-name>
---
apiVersion: v1
kind: Service
metadata:
  name: snp500-backend
spec:
  selector:
    app: snp500-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001