apiVersion: apps/v1
kind: Deployment
metadata:
  name: snp500-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snp500-backend
  template:
    metadata:
      labels:
        app: snp500-backend
    spec:
      containers:
        - name: backend
          image: 694409028280.dkr.ecr.us-east-1.amazonaws.com/snp500-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: snp500-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snp500-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "w210-snp500.cc14g6q8i9nn.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "postgres"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: snp500-api-keys-secret
                  key: OPENAI_API_KEY
            - name: NEWSAPI_AI_KEY
              valueFrom:
                secretKeyRef:
                  name: snp500-api-keys-secret
                  key: NEWSAPI_AI_API_KEY
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: snp500-backend
spec:
  selector:
    app: snp500-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001