apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snp500-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: <your-domain>
      http:
        paths:
          - path: /(api.*)
            pathType: Prefix
            backend:
              service:
                name: snp500-backend
                port:
                  number: 5001
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: snp500-frontend
                port:
                  number: 3000