version: '3.8'

services:
  postgres:
    image: ankane/pgvector  # ✅ Comes with pgvector pre-installed
    container_name: postgres_pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trading_data
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: